apiVersion: apps/v1
kind: Deployment
metadata:
  name: kishore-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kishore
  template:
    metadata:
      labels:
        app: kishore
    spec:
      containers:
      - name: kishore-container
        image: kishoresandy/kishore:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kishore-service
spec:
  selector:
    app: kishore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

